### Create Product
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "title": "Pin",
    "price": 10
}

### Get All Porducts
GET http://localhost:3000/api/products

### Get Single Product
GET http://localhost:3000/api/products/1

### Update Product
PUT  http://localhost:3000/api/products/1
Content-Type: application/json

{
    "title": "Book"
}

### Delete Product
DELETE  http://localhost:3000/api/products/4