### Create Reviews
POST http://localhost:3000/api/reviews
Content-Type: application/json

{
    "rating": 10,
    "comment": "very good"
}

### Get All Reviews
GET http://localhost:3000/api/reviews

### Get Single Review
GET http://localhost:3000/api/reviews/1

### Update Review
PUT  http://localhost:3000/api/reviews/4
Content-Type: application/json

{
    "comment": "good"
}

### Delete Reviews
DELETE  http://localhost:3000/api/reviews/4