### Create User
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Mohammed",
    "email": "mohammed101@gmail.com"
}

### Get All Users
GET http://localhost:3000/api/users

### Get Single User
GET http://localhost:3000/api/users/1

### Update User
PUT  http://localhost:3000/api/users/2
Content-Type: application/json

{
    "name": "Aly"
}

### Delete User
DELETE  http://localhost:3000/api/users/2